title: <p align="center"> Vaidehi </p>
logo: /assets/img/logo.jpeg

description:
  
  Passionate about exploring , playing and enjoying and learning with data.
  Professionally a software developer working on AIOps - Artifical Inteligence for IT operations.
  Been part of many ideathon and hackathon to win or participate in innovation culture of industry and technology
 




theme: jekyll-theme-minimal
