title: <p align="center"> Vaidehi </p>
logo: /assets/img/logo.jpeg

description:
  Data science enthusiast|Software developer|Working on AIOps|Innovation & Technology Geek
  



theme: jekyll-theme-minimal
